CRUD 생성
wecode-bootcamp-korea/41-backend-westagram-3 pull request #15
Opened 2022-12-22 08:53 UTC by kss7082

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Express와 mysql raw 쿼리문을  사용해 CRUD 만들기

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express 와 mysql raw 쿼리문을 이용해 CRUD 만들기

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![스크린샷 2022-12-22 오후 5 34 12](https://user-images.githubusercontent.com/118211014/209095719-95631a33-c562-4af5-bf87-9046d6dc4f38.png)
![스크린샷 2022-12-22 오후 5 39 51](https://user-images.githubusercontent.com/118211014/209095751-f151495a-d852-4a3b-99db-2d47345af1f2.png)
![스크린샷 2022-12-22 오후 5 40 44](https://user-images.githubusercontent.com/118211014/209095767-cbfcc27d-bc9e-4e29-9508-f37dfddcf5d5.png)
![스크린샷 2022-12-22 오후 5 44 55](https://user-images.githubusercontent.com/118211014/209095791-1512cf1f-3509-496a-9eba-be0cd9ab31d1.png)

![스크린샷 2022-12-22 오후 5 46 34](https://user-images.githubusercontent.com/118211014/209095820-722205a1-246e-44ea-99c6-8490538711d1.png)

![스크린샷 2022-12-22 오후 5 49 21](https://user-images.githubusercontent.com/118211014/209095845-ec7562df-a2b8-4c55-9081-ccef7dea2ce3.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-23 01:57 UTC, bigfanoftim requested changes

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +app.post("/postCreate", async (req, res, next) => {
```suggestion
app.post("/post", async (req, res, next) => {
```
- Post 메소드는 주로 새로운 리소스를 생성할 때 사용되는 메소드입니다. 이미 메소드 이름에 충분히 의미가 부여되었으니 URI는 요청에 맞는 자원을 기준으로 작성해 주세요.
    
    ```jsx
    // BAD ❌
    POST :3000/make/post
    POST :3000/create_post
    POST :3000/make_post
    
    // GOOD ✅
    POST :3000/post
    ```

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +  res.status(201).json({ data: data });
상태코드 확인 해주세요!

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +app.get("/posts/:userId", async (req, res, next) => {
```Shell
# BAD
GET :3000/posts/1 # postId가 1인지 userId가 1인지 categoryId가 1인지 파악 불가능

# GOOD
GET :3000/posts/userId/1
```

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +app.patch("/modify/:postId", async (req, res, next) => {
이 부분도 위의 피드백 확인 후 수정해주세요.

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +app.delete("/delete/:postId", async (req, res) => {
여기도 마찬가지입니다.

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +  res.status(201).json({ message: "postingDeleted" });
```suggestion
  res.status(...).json({ message: "postingDeleted" });
```
이 부분도 다시 확인해주세요.

2022-12-23 01:57 UTC, bigfanoftim commented on Seungsu/app.js
> +app.post("/likeuser", async (req, res, next) => {
likeuser는 user 좋아요를 누르는 행위처럼 보이네요.
`like`정도만 되어도 충분할 것 같습니다.

2022-12-23 04:48 UTC, kss7082 commented on Seungsu/app.js
> +app.post("/postCreate", async (req, res, next) => {
네 url 확인하고 수정했습니다.

2022-12-23 04:48 UTC, kss7082 commented on Seungsu/app.js
> +  res.status(201).json({ data: data });
네 상태코드 확인하고 수정했습니다

2022-12-23 04:49 UTC, kss7082 commented on Seungsu/app.js
> +app.get("/posts/:userId", async (req, res, next) => {
네 확인을 위해 /users/를 추가했습니다.

2022-12-23 04:49 UTC, kss7082 commented on Seungsu/app.js
> +app.delete("/delete/:postId", async (req, res) => {
마찬가지로 post 삭제 api이기 때문에 /posts/ 를 추가했습니다.

2022-12-23 04:50 UTC, kss7082 commented on Seungsu/app.js
> +  res.status(201).json({ message: "postingDeleted" });
네 201은 리소스가 생성되었다는 상태코드라 200으로 수정했습니다.

201은 post 나 put 일부에서 사용한다는것을 검색을 토대로 배웠습니다.

2022-12-23 04:50 UTC, kss7082 commented on Seungsu/app.js
> +app.post("/likeuser", async (req, res, next) => {
앞으로 url 조금더 알기쉽도록 주의해서 쓰겠습니다.

2022-12-23 05:47 UTC, bigfanoftim requested changes
해당 피드백 다른 코드에도 전부 적용해주세요1!

2022-12-23 05:47 UTC, bigfanoftim commented on Seungsu/app.js
> +app.patch("/modify/posts/:postId", async (req, res, next) => {
```suggestion
app.patch("/posts/:postId", async (req, res, next) => {
```
제 의도는 아예 modify 자체가 필요없다는 뜻이었습니다~  method에 이미 그 의미가 충분히 담겨있기 때문입니다.

실제로 Github에서 제공하는 API 중 Repository를 생성하는 API의 엔드포인트 주소는 다음과 같습니다.
```Shell
POST {github_url}/orgs/{org_name}/repos
```

2022-12-23 06:33 UTC, kss7082 commented on Seungsu/app.js
> +app.patch("/modify/:postId", async (req, res, next) => {
네 수정했습니다.

2022-12-23 06:37 UTC, kss7082 commented on Seungsu/app.js
> +app.patch("/modify/posts/:postId", async (req, res, next) => {
네 확인했습니다.
method 로 확인가능하기때문에 엔드포인트 주소엔 넣을 필요가없어 modify, delete 삭제 했고, 순서만 바꿔 수정과 삭제를 구분했습니다.

2022-12-23 07:30 UTC, bigfanoftim requested changes
승수님 다 잘 진행됐는데 기능이 동작하려면 선행되어야 할 migration 작업들이 있어야 하는데
PR 브랜치에서는 보이지 않네요. 확인해주세요!

2022-12-23 08:45 UTC, kss7082 commented
> 승수님 다 잘 진행됐는데 기능이 동작하려면 선행되어야 할 migration 작업들이 있어야 하는데 PR 브랜치에서는 보이지 않네요. 확인해주세요!

깃 충돌 해결 하다가 migrations table 파일 두개 날아가서 다시 올렸습니다 !

2022-12-26 03:19 UTC, bigfanoftim requested changes

2022-12-26 03:19 UTC, bigfanoftim commented on Seungsu/db/migrations/20221221014837_create_likes_tables.sql
> +  post_id int not null,
좋아요는 오직 유저 한명, 포스트 하나에 매칭됩니다. 
unique를 추가해서 좋아요가 중복으로 생기지 않도록 해주세요.

2022-12-26 05:23 UTC, kss7082 commented on Seungsu/db/migrations/20221221014837_create_likes_tables.sql
> +  post_id int not null,
네 따로 추가했씁니다

2022-12-26 06:17 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-26 06:18 UTC, merged