[최민주] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/41-backend-westagram-3 pull request #16
Opened 2022-12-23 02:54 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- CRUD 기능 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

- 3 게시글 등록
- 4 전체 게시글 조회
- 5 유저 게시글 조회
- 6 유저 게시글 수정
- 7 게시글 삭제
- 8 좋아요 / 좋아요 취소

<br />

## :: 테스트 결과 이미지

1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
(참고) https://judy-choi.notion.site/20221219-Express-31efda7a921b46ccacd5b86616b2d72e

<br />

## :: 기타 질문 및 특이 사항
- 1 .vscode 폴더가 계속 커밋됩니다. ㅜㅜ gitignore 에 추가되어 있는데도요.
- 2 schema.sql 도요.
- 3 .gitignore 파일은 minjoo 폴더에 넣어두어야 하나요, 아니면 minjoo 폴더와 같은 경로에 넣어두어야 하나요?
- 4 delete 프로토콜은 리턴 시 204 를 권장하는 것으로 알고 있는데, 그러면 리턴 메시지가 안 뜹니다 (그래서 부득이하게 201로 설정했습니다). 원래 이런가요 ㅠㅠ
- 5 꼼꼼한 피드백 감사합니다 🥰

2022-12-23 05:40 UTC, bigfanoftim commented
> 1 .vscode 폴더가 계속 커밋됩니다. ㅜㅜ gitignore 에 추가되어 있는데도요.
> 2 schema.sql 도요.

저번 PR에서의 피드백 한번 확인해보시면 좋을 것 같아요! 한번 커밋된 내역은 gitignore에 추가하는 것으로 해결되지 않습니다!

2022-12-23 05:41 UTC, bigfanoftim commented
> .gitignore 파일은 minjoo 폴더에 넣어두어야 하나요, 아니면 minjoo 폴더와 같은 경로에 넣어두어야 하나요?
app.js와 같은 위치에 놓아주세요.

2022-12-23 05:42 UTC, bigfanoftim commented
> delete 프로토콜은 리턴 시 204 를 권장하는 것으로 알고 있는데, 그러면 리턴 메시지가 안 뜹니다 (그래서 부득이하게 201로 설정했습니다). 원래 이런가요 ㅠㅠ

우선 201은 삭제에 관련된 상태코드가 아니니 204가 안된다고해서 201로 교체하는 것은 좋지 않습니다. 201을 한번 서칭해보세요!
추가로 204 상태코드에 대해서 조금만 더 구글링 해보시면 리턴 메세지가 왜 안나오는지 알 수 있습니다. 한번 확인해보세요!

2022-12-23 05:43 UTC, bigfanoftim requested changes

2022-12-23 05:43 UTC, bigfanoftim commented on minjoo/.gitignore
> +>>>>>>> main
conflict가 제대로 해결되지 않았네요 ㅎㅎ 충돌이 일어나서 그걸 해결하는 과정 중에 다 완벽하게 처리되진 않은 모양입니다.

다시 한 번 말씀드리면 PR을 올리시고 리뷰 요청으로 변경하시기 전에 작성하신 PR의 Files changed를 꼭 확인해주세요.

2022-12-23 06:13 UTC, Judy-Choi commented
> > delete 프로토콜은 리턴 시 204 를 권장하는 것으로 알고 있는데, 그러면 리턴 메시지가 안 뜹니다 (그래서 부득이하게 201로 설정했습니다). 원래 이런가요 ㅠㅠ
> 
> 우선 201은 삭제에 관련된 상태코드가 아니니 204가 안된다고해서 201로 교체하는 것은 좋지 않습니다. 201을 한번 서칭해보세요! 추가로 204 상태코드에 대해서 조금만 더 구글링 해보시면 리턴 메세지가 왜 안나오는지 알 수 있습니다. 한번 확인해보세요!

2022-12-23 06:15 UTC, Judy-Choi commented
> stauts 를 204 로 설정하면 message 가 담긴 body 자체가 리턴되지 않아서 라고 하네요. 리턴메시지가 있어야 해서 일단 201 -> 200 으로 수정했습니다

2022-12-23 06:17 UTC, Judy-Choi commented on minjoo/.gitignore
> +>>>>>>> main
확인했습니다!  HEAD 의 .db/schema.sql 만 ignore 에 추가되도록 하였습니다.

2022-12-23 07:33 UTC, bigfanoftim commented
> stauts 를 204 로 설정하면 message 가 담긴 body 자체가 리턴되지 않아서 라고 하네요. 리턴메시지가 있어야 해서 일단 201 -> 200 으로 수정했습니다

좋습니다~ 👍 궁금하셨던 내용을 검색을 통해 잘 해결셨네요!
스스로 궁금해하는 것을 검색하고 해결하는 습관이 생기면 앞으로 생기는 문제들도 쉽게 해결해나가실 수 있을겁니다~

2022-12-23 07:34 UTC, bigfanoftim requested changes

2022-12-23 07:34 UTC, bigfanoftim commented on minjoo/app.js
> +
불필요한 주석 확인 후 지워주세요~!

2022-12-23 07:34 UTC, bigfanoftim commented on minjoo/db/migrations/20221222024434_likes_table.sql
> +    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
하나의 유저는 하나의 게시글에 여러 좋아요 데이터를 생성할 수 없으니 그에 맞게 unique를 걸어주세요.

2022-12-23 08:32 UTC, Judy-Choi commented on minjoo/app.js
> +
삭제하겠습니다 🫡

2022-12-23 08:37 UTC, Judy-Choi commented on minjoo/db/migrations/20221222024434_likes_table.sql
> +    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
- migration/likes_table.sql 파일에 CONSTRAINT likes_ukey UNIQUE (user_id, post_id) 추가 완료
- likes 테이블에 unique 추가 완료 (ALTER TABLE likes ADD CONSTRAINT likes_ukey UNIQUE (user_id, post_id);)

2022-12-23 09:48 UTC, Judy-Choi commented
수정사항 반영했습니다. 한 주 동안 감사했습니다 🥰
git 은 항상 어려웠는데 이번 기회에 멘토님 덕분에 감을 좀 잡을 수 있었어요. 
불금 && 즐거운 주말 && 메리크리스마스 입니다 멘토님! 😍🎄

2022-12-26 03:19 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-26 03:20 UTC, merged