[권태령] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/41-backend-westagram-3 pull request #18
Opened 2022-12-23 11:44 UTC by taegoori

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-24 06:07 UTC, sangwoong03 reviewed
고생하셨습니다 태령님!

해당 작업을 계속 커밋하고 푸시하시면서 git 명령어에 대해 익숙해지는 것이 좋을 것 같습니다!

또한 초기 세팅 관련해서 westudy의 자료를 보시면서 부족한 파일을 추가해주세요~!

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +const http = require ("http");
express를 이용하기 때문에 http 내장 모듈을 사용할 필요가 없습니다.

해당 코드는 삭제해주세요!

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +})
11번 라인의 코드를 보면 `app.use(cors())`를 통해 cors()함수를 미들웨어로 등록하고 있습니다.

그렇기 때문에 19번~21번 라인에서 미들웨어로 다시 cors()함수를 등록할 필요가 없습니다!

또한 콜백함수로 화살표 함수 `() => {}`와 같은 형태로 작성하면 더욱 간결한 콜백함수를 작성할 수 있으니 15~17번 라인의 코드처럼 작성하는 것이 좋을 것 같습니다! 

``` suggestion
app.get('/ping', (req, res) => {
  return res.json({ message: 'pong'  })
})
``

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +app = express()
상수 변수를 선언하기 위해 const 키워드를 붙여주세요!
```suggestion
const app = express()
```

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +const server = http.createServer(app)
8번 라인에서 app이라는 변수에 `express()` 를 할당하여 사용하기 떄문에 http 내장 모듈을 이용한 서버를 만드는 것이 불필요할 것 같습니다!

해당 코드는 삭제해주세요!

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +const PORT = process.env.PORT;
`process.env.변수명`을 사용하기 위해서는 `.env` 파일이 필요합니다.

작업 폴더 내부에 `.env` 파일을 생성하여 알맞은 환경변수를 작성해주세요!

2022-12-24 06:07 UTC, sangwoong03 commented on Taeryoung/app.js
> +}
`server`라는 변수에 할당된 서버를 띄울 수 있는 객체는 http 내장 모듈을 이용한 것이기 때문에 앞서 리뷰드린대로 해당 프로젝트에서는 불필요한 코드입니다.

이에 따라 8번 라인에서 선언한 `app` 이라는 변수를 이용하여 서버를 띄워야 합니다.
```suggestion
const start = async () => {
    app.listen(PORT, () => console.log(`server is listening on ${PORT}`));
}
```

2022-12-27 04:47 UTC, taegoori commented on Taeryoung/app.js
> +})
next가 없을 때 모듈에서 경로가 꼬인다고 오류가 나는 것 같습니다.

2022-12-27 05:03 UTC, bigfanoftim requested changes
태령님! 간단한 수정사항이니 빠르게 적용 후 푸시해주세요!

2022-12-27 05:03 UTC, bigfanoftim commented on Taeryoung/app.js
> +    app.get('/ping', cors(), function (req, res, next) {
```suggestion
    app.get('/ping', function (req, res, next) {
```
위에서 `app.use(cors())` 코드를 작성함으로써 cors 관련 처리가 이미 되어있는 것 같아요.

추가로 express에서 활용하는 middleware 패턴은 request가 들어와 API가 호출될 때까지 중간에 거쳐가는 다리라고 생각하시면 됩니다.

2022-12-27 05:23 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-27 05:23 UTC, merged