[최민주] Assignment 2: Bcrypt Verification 및 JWT 발급하기
wecode-bootcamp-korea/41-backend-westagram-3 pull request #22
Opened 2022-12-26 07:19 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Bcrypt Verification 및 JWT 발급하기
- 로그인 정보 확인 & JWT 토큰 발급

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

1. 입력받은 email 과 매치되는 hashedPassword 를 DB 로부터 가져오기
2. password 와 DB 에서 가져온 hashedPassword 가 일치하는지 체크
2-1. 일치하면 JWT 발급
2-2. 다르면 "message" : "Invalid User" 띄우기

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="646" alt="image" src="https://user-images.githubusercontent.com/53294075/209516792-ea9b870c-ab57-4e81-8629-02eba6cd81c1.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/53294075/209516871-c68152aa-b69c-408a-a5ff-7bbfa3d9e801.png">

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![image](https://user-images.githubusercontent.com/53294075/209516575-368f078d-3052-411b-9972-76e8789e177d.png)

<br />

## :: 기타 질문 및 특이 사항
- 항상 감사합니다 멘토님 🙇‍♀️

2022-12-26 07:51 UTC, Judy-Choi commented
```
  // 2. password 와 DB 에서 가져온 hashedPassword 가 일치하면
  // 2-1. JWT 발급
  if (await bcrypt.compare(password, hashedPassword)) {
    // 실제로 전달할 내용인 Payload 정의
    const payLoad = {
      email: email,
      password: hashedPassword,
    };

    // sign() method로 JWT 발급, 첫번째 인자로 Payload가 두번째 인자로 Secret Key가 들어 갑니다.
    // 세번째 인자로 option을 추가 할 수 있는데, option이 존재하지 않으면 HS256 알고리즘으로 JWT가 발급 됩니다.
    const jwtToken = jwt.sign(payLoad, secretKey); // (4)
    res.status(200).json({ accessToken: jwtToken });
  }
```

이 부분이 일단 정상동작하는데 제가 맞게 이해하고 짠 건지 모르겠습니다 😂

(1) 프론트에서 전달받은 password 와 DB에서 가져온 hashedPassword 를 bcrypt.compare() 써서 비교하는 게 맞는지
(2) payLoad 에 넣어주는 password 가 프론트에서 전달받은 password 여야 하는지 hashedPassword 여야 하는지

2022-12-26 08:43 UTC, Judy-Choi commented
3번 토큰 추가 과제하던 게 push 되어서 코드 일부 삭제했습니다 😂😂

2022-12-27 02:51 UTC, bigfanoftim requested changes

2022-12-27 02:51 UTC, bigfanoftim commented on minjoo/app.js
> +  }
early return 패턴을 적용하면 더 로직이 깔끔할 것 같습니다.

```JavaScript
if (..) { 
  res.status(401)...
}

// logic
res.status(200)...
```

2022-12-27 04:32 UTC, Judy-Choi commented on minjoo/app.js
> +  }
저 과제 3번 완성한 이후에 피드백 받았는데 과제 3에 early return 적용해도 되나요? 😂

2022-12-27 06:54 UTC, bigfanoftim commented on minjoo/app.js
> +  }
넵~

2022-12-27 06:54 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-27 06:54 UTC, merged