[백종호] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/41-backend-westagram-3 pull request #3
Opened 2022-12-20 04:44 UTC by JongHoB

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Express API - 초기 환경 세팅

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express API - 초기 환경 세팅

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![Assignment_1](https://user-images.githubusercontent.com/78012131/208585454-da8b593c-4531-43a1-9537-9a955210c801.jpg)

<br />

## :: 기타 질문 및 특이 사항
-

2022-12-20 04:56 UTC, bigfanoftim requested changes
이미지 파일은 지워서 올려주세요~

추가로 코드 가독성을 위해 학습 자료에 있는 prettier를 적용해 보세요!

2022-12-20 05:32 UTC, jbaik99 commented
이미지 지웠습니다!

2022-12-20 06:13 UTC, bigfanoftim requested changes
<img width="741" alt="image" src="https://user-images.githubusercontent.com/62135254/208596520-564cb09a-88fd-46e9-a6ee-d8bb383f9121.png">

여전히 이미지가 올라와있네요~
코드에 올라온 이미지를 지워달라는 의미였습니다. 설명창에는 항상 이미지를 첨부해주세요~

2022-12-20 06:54 UTC, JongHoB commented
코드에서 이미지 지웠고,
설명창에 이미지 첨부했습니다.

2022-12-20 08:28 UTC, bigfanoftim requested changes

2022-12-20 08:28 UTC, bigfanoftim commented on JongHo/app.js
> +);
들여쓰기나 띄어쓰기가 전부 제각각인 것 같아요. Prettier 학습 자료 참고하셔서 포맷팅 해주세요!

2022-12-21 01:05 UTC, JongHoB commented on JongHo/app.js
> +);
prettier 적용해서 다시 올렸습니다.

2022-12-21 02:04 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-21 02:04 UTC, merged