Feature/minjoo
wecode-bootcamp-korea/41-backend-westagram-3 pull request #4
Opened 2022-12-20 06:36 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Express 초기 환경세팅

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- Express 초기 환경 설정
- TypeORM / dbConnection 설정

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 😭

2022-12-21 02:07 UTC, bigfanoftim requested changes
![image](https://user-images.githubusercontent.com/62135254/208803528-9f8e156a-7d8b-4d20-b8e5-5a4c1b3226b6.png)

다른 사람들과 하나의 레파지토리에서 작업하는 프로젝트이니 함부로 동료들의 코드를 삭제하면 안됩니다.

2022-12-21 02:07 UTC, bigfanoftim commented on minjoo/.env.sample
> +TYPEORM_LOGGING =TRUE
뭔가 진짜 환경변수를 작성하신 것 같아 보이는데 만약 맞다면 sample 파일에는 sample 코드를 작성해주세요.

2022-12-21 02:07 UTC, bigfanoftim commented on minjoo/app.js
> +// });
불필요한 주석 지워주세요.

2022-12-21 04:51 UTC, Judy-Choi commented on minjoo/.env.sample
> +TYPEORM_LOGGING =TRUE
- [x] 코드 삭제할 때 주의하겠습니다.
- [x] .env.sample 값 수정하고 커밋했습니다!

2022-12-21 04:57 UTC, bigfanoftim commented on minjoo/.env.sample
> +TYPEORM_LOGGING =TRUE
수정 후 푸시를 안해주신것 같아요~ 확인 부탁드립니다.

2022-12-21 05:04 UTC, Judy-Choi commented on minjoo/.env.sample
> +TYPEORM_LOGGING =TRUE
방금 푸시했습니다!

2022-12-21 06:43 UTC, bigfanoftim commented
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/62135254/208838379-05bf6eb8-4ada-4c20-bb81-7f3908b21175.png">

여전히 동기분의 파일을 삭제한 상태이네요. 항상 PR을 올리시고 동료들에게 리뷰요청을 진행하실 때에는 본인이 작업한 내용이 무엇인지 PR 내 Files changed를 확인 후 진행해야 합니다.

우선 지금 상황에서는 commit을 다루는 것이 쉽지 않을테니 현재 branch에 존재하는 코드를 다른 브랜치로 옮겨 새롭게 PR 올리시는 것을 추천드립니다. 
- checkout 전 수정 사항 모두 현재 브랜치에 add & commit
- `git checkout main`
- `git checkout -b feature/..`
위 순서를 따라 새로운 브랜치를 생성하시고 현재 브랜치에 담긴 코드를 그대로 옮겨주세요.

이미 파일을 삭제한 commit을 계속해서 지닌 상태로 푸시하기 때문에 파일 삭제 내역이 올라오지 않을 수 업는 상태입니다.

2022-12-22 01:49 UTC, Judy-Choi commented
새 브랜치에 PR 했습니다. 이 풀리퀘는 삭제할까요?

2022-12-22 02:23 UTC, bigfanoftim commented
이 PR은 제가 닫겠습니다~!

2022-12-22 02:23 UTC, closed without merging