[최민주] Assignment 2: Express API - 유저 회원가입 추가
wecode-bootcamp-korea/41-backend-westagram-3 pull request #9
Opened 2022-12-21 05:23 UTC by Judy-Choi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유저 회원가입 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 유저 회원가입 기능 추가 (app.post("/users", async (req, res) ~~)
- 성공 시 201 리턴

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://user-images.githubusercontent.com/53294075/208827730-bec42648-fbee-4171-8403-669226079e3c.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![스크린샷 2022-12-20 17 50 57](https://user-images.githubusercontent.com/53294075/208827868-55104237-c13e-4ff0-9d1a-99aa265e4b1f.png)

3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/53294075/208827609-2046ef7f-7659-4358-802c-4f8205070564.png">

<br />

## :: 기타 질문 및 특이 사항
- id 를 입력하지 않아도 DB에 저장될 때 자동으로 id가 1씩 증가되면서 저장하게 하는 방법이 없을까요? 🤓

2022-12-21 06:50 UTC, bigfanoftim commented
> id 를 입력하지 않아도 DB에 저장될 때 자동으로 id가 1씩 증가되면서 저장하게 하는 방법이 없을까요?

우선 primary key로 지정한 컬럼은 아마 자동으로 처리가 될겁니다~ 
사실 이 부분은 당연한 것이 데이터를 추가할때마다 어떤 id를 넣을지 판단하는 것은 불가능합니다. 왜냐하면  id는 고유값인데 어떤 고유값이 DB에 있는지 매번 판단할 수 없기 때문입니다.

2022-12-21 06:51 UTC, bigfanoftim requested changes
Assignment 1부터 빠르게 적용 부탁드립니다~

2022-12-22 02:22 UTC, Judy-Choi commented
Assign #1 적용하고 #2 도 완료했습니다!
(항상 감사합니다 🥰)

2022-12-22 02:27 UTC, bigfanoftim commented
> Assign #1 적용하고 #2 도 완료했습니다! (항상 감사합니다 🥰)

<img width="985" alt="image" src="https://user-images.githubusercontent.com/62135254/209041387-ed0d5728-1ba7-4ce7-becc-c47c30792252.png">

해당 Conflict 안내는 기존의 과제1 브랜치에서 그대로 과제2 브랜치를 생성하고 작업을 하셨기 때문에
과제1의 내용이 변경됨에 따라 아마 과제2 브랜치, 즉 현재 브랜치에 충돌이 생길 수 있다는 안내 문구입니다.

```Shell
$ git add .
$ git commit -m "commit message"
$ git checkout main
$ git pull origin main
$ git checkout feature/assign2 # 이번 PR에 해당하는 브랜치로 이동
$ git merge main # main에 업데이트된 내용을 현재 내 브랜치로 통합
```
위의 명령어를 터미널에서 순차적으로 입력하면 최종적으로 충돌이 일어난 코드 블럭이 현재 개발하고 계시는 IDE(Vscode, Intellij 등)에서 보이게 될겁니다. 해당 부분을 의도에 맞게, 즉 기능이 전부 완전히 올바르게 동작할 수 있도록 수정 후 

```Shell
git add .
git commit -m "..."
```
이전과 동일하게 진행해주시면 됩니다.

2022-12-22 02:28 UTC, bigfanoftim requested changes

2022-12-22 02:28 UTC, bigfanoftim commented on minjoo/app.js
> +});
dbmate 관련 파일이 올라오지 않았네요 확인해주세요~!

2022-12-22 02:28 UTC, bigfanoftim commented on minjoo/app.js
> +  const { id, name, email, profile_image, password } = req.body;
```suggestion
  const { id, name, email, profileImageUrl, password } = req.body;
```
- JavaScript에서는 기본적으로 `snake_case`가 아닌 `CamelCase`로 작성합니다.
- 또한 snake_case, CamelCase를 뒤죽박죽 섞어서 사용하면 안됩니다.
- 하나의 컨벤션으로 통일해서 작성해 주세요.

2022-12-22 04:40 UTC, Judy-Choi commented on minjoo/app.js
> +});
dbmate 업로드했습니다!

2022-12-22 04:40 UTC, Judy-Choi commented on minjoo/app.js
> +  const { id, name, email, profile_image, password } = req.body;
컨벤션 통일했습니다!

2022-12-22 04:41 UTC, Judy-Choi commented
충돌 일어난 코드블럭 확인하고 커밋했는데 여전히 Merging is blocked 뜨는 것 같습니다...

2022-12-22 06:07 UTC, bigfanoftim commented
> 충돌 일어난 코드블럭 확인하고 커밋했는데 여전히 Merging is blocked 뜨는 것 같습니다...

음 제가 봤을때는 컨플릭트는 잘 해결된 것으로 보입니다! 말씀하신 문구는 누군가의 approve없이 함부로 머지할 수 없도록 권한을 막아두었기에 나오는 문구이니 신경쓰실 필요는 없습니다.

2022-12-22 06:09 UTC, bigfanoftim requested changes
users를 제외한 다른 migration 파일은 이번 PR과는 상관이 없는 코드입니다. 
PR을 작성하실 때에는 미래를 내다보고 미리 작업한 내용은 추가하지 마시고
해당 PR에 꼭 해당하는 내용만 담도록 해주세요.

2022-12-22 06:09 UTC, bigfanoftim commented on minjoo/db/migrations/20221222021045_posts_table.sql
> +DROP TABLE posts;
- 과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-12-22 06:09 UTC, bigfanoftim commented on minjoo/db/migrations/20221222024434_likes_table.sql
> +-- migrate:up
여기도 마찬가지입니다.

2022-12-22 06:09 UTC, bigfanoftim commented on minjoo/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- `schema.sql`은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 `.gitignore`에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-12-22 06:15 UTC, Judy-Choi commented on minjoo/db/migrations/20221222021045_posts_table.sql
> +DROP TABLE posts;
cover_image VARCHAR(1100) NOT NULL 삭제하고 커밋하겠습니다.

2022-12-22 06:16 UTC, Judy-Choi commented on minjoo/db/migrations/20221222021045_posts_table.sql
> +DROP TABLE posts;
posts, likes table.sql 삭제 후 재커밋하겠습니다~!

2022-12-22 06:16 UTC, Judy-Choi commented on minjoo/db/migrations/20221222024434_likes_table.sql
> +-- migrate:up
posts, likes table.sql 삭제 후 재커밋하겠습니다~!

2022-12-22 06:16 UTC, Judy-Choi commented on minjoo/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
설정했습니다!

2022-12-22 06:43 UTC, bigfanoftim requested changes

2022-12-22 06:43 UTC, bigfanoftim commented on minjoo/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
제가 그룹 토의때 말씀드렸던 상황이 여기서 발생했습니다!

이미 git이 트래킹하고 있는 것들은 단순히 ignore에 추가한다고 해결되지 않습니다. 
추가로 이상태로 리뷰 요청으로 바꾸셨다는 뜻은 새로운 커밋을 푸시하시고 실제로 내가 어떤 파일들을 푸시했는지 확인하지 않았다는 반증입니다. 개발자는 사람이기 때문에 절대로 내가 어떤 코드를 작성했는지 100퍼센트 기억할 수 없습니다.
따라서 정말 중요한 환경 변수 혹은 이상한 것들이 올라오진 않았는지 무조건 확인하는 습관을 길러야 합니다.

2022-12-23 01:17 UTC, Judy-Choi commented on minjoo/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
확인했습니다 😂 푸시 다시 했고 ignore 파일들 제거되었는데 이러면 문제 없는건가요?

2022-12-23 01:27 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-23 01:27 UTC, merged